# Generated by Django 4.2.27 on 2025-12-19 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecyclingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('item_name_ko', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('guide', models.TextField()),
                ('tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='guide_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('plastic', '플라스틱'), ('glass', '유리'), ('paper', '종이류'), ('metal', '고철'), ('food', '음식물쓰레기'), ('general', '일반쓰레기'), ('large', '대형폐기물'), ('electronic', '폐가전'), ('clothes', '의류'), ('other', '기타')], default='other', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recycling_images/%Y/%m/%d/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date', '-created_date'],
            },
        ),
    ]
